### ISSUE TITLE
Home Pin hard to find

### ISSUE THREAD

**Issue by MariaBianchi** [votinginfoproject/gttp-relaunch#122]
One of the pieces of feedback we received from the folks at FB, and that I'm finding to be extremely true as I test, particularly in cases like WA where there are a lot of sites, is that the home pin is really hard to distinguish. 

Troy suggested that one way to make it pop would be to invert the colors for that marker. 

Do you have any other ideas, @mollieru? If you don't have a different preferred solution, could you create that inverted marker for me?

**Comment by mollieru** [comment]
I believe this was resolved when we made the map pins different shades. let me know if it's still an issue.
