### ISSUE TITLE
revised Logo Colors

### ISSUE THREAD

**Issue by MariaBianchi** [votinginfoproject/gttp-relaunch#88]
@mollieru I might be misremembering, but I think in the original mockups, you'd shifted the coloring of the logo slightly to match the theme. If that's the case, we might need that redone with the new, higher res version of the logo that was unearthed finally.
[VIP-Logo-20180412.zip](https://github.com/votinginfoproject/gttp-relaunch/files/1943101/VIP-Logo-20180412.zip)

**Comment by mollieru** [comment]
Revised logo w tweaked colors in .svg and .png here: 
[logo-icon.zip](https://github.com/votinginfoproject/gttp-relaunch/files/2031265/logo-icon.zip)
